spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:orders
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8083
